# Default values for jellyfin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/jellyfin/jellyfin
  tag: "10.9.1"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Setting this to true enables DLNA which requires the pod to be attached to the
# host network in order to be useful - this can break things like ingress to the service
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#hosts-namespaces
# https://jellyfin.org/docs/general/networking/dlna.html
enableDLNA: false

service:
  type: ClusterIP
  port: 8096
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # ingressClassName: nginx
  path: /
  hosts:
    - jellyfin.local
  tls: []
  #  - secretName: jellyfin-tls
  #    hosts:
  #      - jellyfin.local

persistence:
  config:
    enabled: false
    ## jellyfin configuration data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    # subPath: some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    ## If you neither want to create a PVC, nor use a pre-existing one,
    ## but instead want to use a custom volume, simply set and configure
    ## the customVolume section with your volume definition.
    ## This can be useful, for instance, to hook into an NFS endpoint
    ## by creating an NFS volume.
    ## persistence.config.enabled takes precedence over the custom volume definition
    ## so make sure to set it to false if you intend to use a custom volume.
    # customVolume:
    #   nfs:
    #     server: my-nfs-server.example.com
    #     path: /my-nfs-volume
    #     readOnly: false
  media:
    enabled: false
    ## Directory where media is persisted
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    # subPath: some-subpath
    accessMode: ReadWriteOnce
    size: 10Gi
    ## If you neither want to create a PVC, nor use a pre-existing one,
    ## but instead want to use a custom volume, simply set and configure
    ## the customVolume section with your volume definition.
    ## This can be useful, for instance, to hook into an NFS endpoint
    ## by creating an NFS volume.
    ## persistence.media.enabled takes precedence over the custom volume definition
    ## so make sure to set it to false if you intend to use a custom volume.
    # customVolume:
    #   nfs:
    #     server: my-nfs-server.example.com
    #     path: /my-nfs-volume
    #     readOnly: false
  extraExistingClaimMounts: []
    # - name: external-mount
    #   mountPath: /srv/external-mount
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    #   existingClaim:
    #   readOnly: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: []
  #- name: renderD129
  #  hostPath:
  #    path: /dev/dri/renderD129

extraVolumeMounts: []
  #- mountPath: /dev/dri/renderD129
  #  name: renderD129

extraPodLabels: {}

extraEnvVars: []
  #- name: MY_ENV_VAR
  #  value: my-env-var-value

# additional annotations applied to the pod
extraPodAnnotations: {}

extraContainers: {}

# Larger libraries may need to increase the readinessProbe and livenessProbe timeouts. Start by increasing the initialDelaySeconds.
livenessProbe:
  enabled: true
  # failureThreshold: 3
  initialDelaySeconds: 10
  # periodSeconds: 10
  # successThreshold: 1
  # timeoutSeconds: 1

readinessProbe:
  enabled: true
  # failureThreshold: 3
  initialDelaySeconds: 10
  # periodSeconds: 10
  # successThreshold: 1
  # timeoutSeconds: 1
